"""PassQuiz revision

Revision ID: 5f75d3b2d2c8
Revises: d28b39ec68fe
Create Date: 2022-09-04 01:48:54.558019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f75d3b2d2c8'
down_revision = 'd28b39ec68fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quiz_result_quiz_id_key', 'quiz_result', type_='unique')
    op.drop_constraint('quiz_result_user_id_key', 'quiz_result', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('quiz_result_user_id_key', 'quiz_result', ['user_id'])
    op.create_unique_constraint('quiz_result_quiz_id_key', 'quiz_result', ['quiz_id'])
    # ### end Alembic commands ###
