"""QuizRes revision

Revision ID: d28b39ec68fe
Revises: b88fbb98a70e
Create Date: 2022-09-04 01:14:14.712736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28b39ec68fe'
down_revision = 'b88fbb98a70e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_result', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'quiz_result', ['quiz_id'])
    op.create_foreign_key(None, 'quiz_result', 'quizzes', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_result', type_='foreignkey')
    op.drop_constraint(None, 'quiz_result', type_='unique')
    op.drop_column('quiz_result', 'quiz_id')
    # ### end Alembic commands ###
